[workspace]
git_only = true
publish = false
release = false
release_always = false
semver_check = false
dependencies_update = false
pr_branch_prefix = "release-plz-"
pr_labels = ["release"]
pr_name = "chore: release @firna/ui v{{ version }}"
git_tag_name = "v{{ version }}"
git_release_name = "@firna/ui v{{ version }}"
changelog_path = "CHANGELOG.md"

[[package]]
name = "firna-ui-release"
changelog_update = true
git_release_enable = true
release = true
