/**
 * Icon glyphs, native resolution.
 *
 * Every icon the library draws itself is imported through this module, so the
 * icon backend is decided in one place: `lucide-react-native` on iOS and
 * Android, `lucide-react` on web (see `icons.web.ts`). The two packages ship
 * the same glyph names, so both modules export an identical list; a unit test
 * keeps them in sync. Add a glyph here only when a component needs it, and add
 * it to the web module in the same change.
 */
export type { IconComponent, IconComponentProps } from "./iconTypes";
export {
  Archive,
  ArrowDownAZ,
  ArrowDownToLine,
  ArrowLeftToLine,
  ArrowRightToLine,
  ArrowUpAZ,
  ArrowUpToLine,
  Bell,
  Bold,
  Brain,
  Calendar,
  CalendarDays,
  Check,
  ChevronDown,
  ChevronFirst,
  ChevronLast,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  CircleAlert,
  CircleCheck,
  CircleX,
  ClipboardPaste,
  Clock,
  Code,
  Columns2,
  Copy,
  CopyPlus,
  CornerUpLeft,
  DollarSign,
  Download,
  Eraser,
  Eye,
  EyeOff,
  GitBranch,
  Grid2x2,
  GripHorizontal,
  GripVertical,
  Hash,
  Heading1,
  Heading2,
  Heading3,
  Headphones,
  Image,
  Inbox,
  Info,
  Italic,
  LayoutGrid,
  List,
  ListChecks,
  ListOrdered,
  LoaderCircle,
  Lock,
  LockOpen,
  Mail,
  Maximize2,
  Mic,
  Minus,
  MoreHorizontal,
  Music,
  Paperclip,
  Pause,
  Pencil,
  Pilcrow,
  Pin,
  Play,
  Plus,
  Redo2,
  Repeat,
  RotateCcw,
  Scissors,
  Search,
  Settings,
  ShieldQuestionMark,
  SkipBack,
  SkipForward,
  Sparkles,
  SquareTerminal,
  Strikethrough,
  Table,
  Tags,
  TextQuote,
  Trash2,
  TriangleAlert,
  Type,
  Undo2,
  User,
  Video,
  Volume2,
  VolumeX,
  X,
  Zap,
} from "lucide-react-native";
